In [284]:
using Pkg
using LinearAlgebra

# Problem 1

In [285]:
A = [1 2; 3 -1]
B = [3 -2; 2 1]
C = [1; 2; 3]
D = [1 3 1; -2 1 -1]
E = [3 1; 0 3; -2 2]
F = [2 1 2; -1 3 -2]

; # don't print F to console

### 1a)

In [286]:
print("Product AB: ")
A*B

Product AB: 

2×2 Matrix{Int64}:
 7   0
 7  -7

In [287]:
print("Product CD: ")
C*D
# Error, mismatch in array dims. C is 3 x 1, D is 2 x 3

Product CD: 

LoadError: DimensionMismatch: matrix A has axes (Base.OneTo(3),Base.OneTo(1)), matrix B has axes (Base.OneTo(2),Base.OneTo(3))

In [ ]:
print("Product EF: ")
E*F

Product EF: 

3×3 Matrix{Int64}:
  5  6   4
 -3  9  -6
 -6  4  -8

### 1b)

In [ ]:
print("Product A^T B:")
A'B

A^T B

2×2 Matrix{Int64}:
 9   1
 4  -5

In [ ]:
print("Product A^T B:")
A'B

Product A^T B:

2×2 Matrix{Int64}:
 9   1
 4  -5

In [ ]:
print("Product B D^T:")
B*D'
# Error in dim mismatch, B is 2 x 2, D^T is 3 x 2.

Product B D^T:

LoadError: DimensionMismatch: matrix A has axes (Base.OneTo(2),Base.OneTo(2)), matrix B has axes (Base.OneTo(3),Base.OneTo(2))

In [ ]:
print("Product D^T F^T:")
D'F' # Error, dim mismatch. D^T is 3 x 2, F^T is 3 x 2

Product D^T F^T:

LoadError: DimensionMismatch: matrix A has axes (Base.OneTo(3),Base.OneTo(2)), matrix B has axes (Base.OneTo(3),Base.OneTo(2))

# Problem 2

In [ ]:
M = [1 0 1; 2 2 3; 1 2 4]

3×3 Matrix{Int64}:
 1  0  1
 2  2  3
 1  2  4

In [ ]:
inv(M)

3×3 Matrix{Float64}:
  0.5    0.5   -0.5
 -1.25   0.75  -0.25
  0.5   -0.5    0.5

In [ ]:
M*inv(M)

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

# Problem 3

In [ ]:
P = [3 -2 -6; -6 -3 -2; -2 6 -3] ./ 7

3×3 Matrix{Float64}:
  0.428571  -0.285714  -0.857143
 -0.857143  -0.428571  -0.285714
 -0.285714   0.857143  -0.428571

In [ ]:
P'P 

3×3 Matrix{Float64}:
  1.0          2.77556e-17  -1.38778e-17
  2.77556e-17  1.0           0.0
 -1.38778e-17  0.0           1.0

In [ ]:
P*P'

3×3 Matrix{Float64}:
  1.0          -2.77556e-17   0.0
 -2.77556e-17   1.0          -1.38778e-17
  0.0          -1.38778e-17   1.0

These are both, up to some floating point error, equal to the identity.

# Problem 4

In [ ]:
A = [-1 3 5 2;
      1 9 8 4;
      0 1 0 1;
      1 1 1 -1]

b = [10; 15; 2; -3]
;

In [ ]:
A \ b

4-element Vector{Float64}:
  4.666666666666659
 -4.333333333333327
  2.999999999999997
  6.333333333333328

In [ ]:
det(A)

-2.9999999999999987

# Problem 5

In [ ]:
A = [4 -1 -1  0;
    -1  4  0 -1;
    -1  0  4 -1;
     0 -1 -1  4]

b = [1; 2; 0; 1]
;

In [ ]:
c = [1;2;3]
d = [2;4;6]

3*ones(length(c))

3-element Vector{Float64}:
 3.0
 3.0
 3.0

In [ ]:
# set number of iterations
function gauss_seidel_iter(A, b; iter = 25, init_guess = nothing)
    U = triu(A) - diagm(diag(A)) # strictly upper triangular part of A
    L = tril(A)               # lower triangular (with diag) part of A

    if isnothing(init_guess)
        init_guess = [0; 0; 0; 0]
    end 

    x = init_guess
    for i ∈ 1:iter
        x_new = L \ (b - U * x)
        x = x_new
    end

    return x
end

# error less than set tolerance
function gauss_seidel_tol(A, b; tol = 1e-5, init_guess = nothing)
    U = triu(A) - diagm(diag(A)) # strictly upper triangular part of A
    L = tril(A)               # lower triangular (with diag) part of A

    true_x = A \ b
    max_error = tol * ones(length(b)) 

    if isnothing(init_guess)
        init_guess = [0; 0; 0; 0]
    end 

    x = init_guess
    error = 1e8 * ones(length(b))
    iterations = 0
    while error > max_error
        x_new = L \ (b - U * x)
        x = x_new
        error = abs.(true_x - x)
        iterations += 1
    end
    print("Iterations 'til convergence: $iterations")
    print("\nTrue solution: x = $true_x")
    print("\nIterative solution: x = $x")
end

gauss_seidel_tol (generic function with 1 method)

In [ ]:
x = gauss_seidel_tol(A,b, tol = 1e-5)

Iterations 'til convergence: 9
True solution: x = [0.5, 0.75, 0.25, 0.5]
Iterative solution: x = [0.49999427795410156, 0.7499971389770508, 0.24999713897705078, 0.4999985694885254]

In [ ]:
A \ b

4-element Vector{Float64}:
 0.5
 0.75
 0.25
 0.5

# Problem 6

### Inverse:

\begin{align*}
    \mathsf{A} \vec{x}_i = \vec{e}_i \tag{4.99} \\
    \mathsf{L}(\mathsf{U}\vec{x_i}) = \vec{e}_i
\end{align*}

Inverse of $\mathsf{A}$ is found by forward substitution with $\mathsf{L}$ and $\vec{e_i}$, giving $\vec{y}_i$, then back substitution with $\mathsf{U}$ and $\vec{y}_i$ to get $\vec{x_i}$, which are the columns of the matrix inverse.

In [ ]:
function fwd_sub(L, b)
    n = length(b)
    x = zeros(n)

    for i ∈ 1:n
        x[i] = (b[i] - dot(L[i,1:i-1], x[1:i-1])) / L[i,i]
    end

    return x
end

function back_sub(U, b)
    n = length(b)
    x = zeros(n)

    for i in n:-1:1
        x[i] = (b[i] - dot(U[i,i+1:end], x[i+1:end])) / U[i,i]
    end

    return x
end
;

In [ ]:
function lu_inverse(A)
    A = float.(A)
    L, U = lu(A)
    n = length(diag(A))

    A_inv = zeros(n,n)

    for i ∈ 1:n
        e_i = zeros(n)
        e_i[i] = 1

        y = fwd_sub(L,e_i)
        x = back_sub(U,y)

        A_inv[:, i] = x
    end

    return A_inv
end

lu_inverse (generic function with 1 method)

In [ ]:
lu_inverse(A)

4×4 Matrix{Float64}:
 0.291667   0.0833333  0.0833333  0.0416667
 0.0833333  0.291667   0.0416667  0.0833333
 0.0833333  0.0416667  0.291667   0.0833333
 0.0416667  0.0833333  0.0833333  0.291667

In [ ]:
inv(A)

4×4 Matrix{Float64}:
 0.291667   0.0833333  0.0833333  0.0416667
 0.0833333  0.291667   0.0416667  0.0833333
 0.0833333  0.0416667  0.291667   0.0833333
 0.0416667  0.0833333  0.0833333  0.291667

### Determinant

\begin{align*}
    \det{\mathsf{A}}
    = \det \mathsf{L} \det{\mathsf{U}}
    = \left(\prod_{k=1}^n 1\right)\left(\prod_{k=1}^n U_{kk}\right) = \prod_{k=1}^n U_{kk}
\end{align*}

In [ ]:
prod([1;2;3])

6

In [ ]:
function lu_det(A)
    A = float.(A)
    L, U = lu(A)

    return prod(diag(U))
end

lu_det (generic function with 1 method)

In [ ]:
lu_det(A)

192.0

In [ ]:
det(A)

192.0

# Problem 7

In [ ]:
A = [0.780 0.563; 0.913 0.659]
b = [0.217; 0.254]

x_exact = [1;-1]
x_α = [0.999, -1.001]
x_β = [0.341, -0.087]
;

In [ ]:
r_α = b - A*x_α

2-element Vector{Float64}:
 0.0013429999999998998
 0.0015720000000000178

In [ ]:
r_β = b - A*x_β

2-element Vector{Float64}:
 9.99999999945489e-7
 0.0

No, the more accurate solution has a *larger* residual than the less accurate solution.

In [ ]:
det(A)

1.0000000001226806e-6

Yes, the determinant being so close to 0 means this matrix is ill-conditioned, which is why there is numerical weirdness.

In [ ]:
A \ b

2-element Vector{Float64}:
  0.9999999998902543
 -0.999999999847955

This solution vector tells us that the bad solution is bad and the good solution is good.

# Problem 8

\begin{align*}
    \vec{q}_j^{\,\,,} &= \vec{q}_j - \sum_{i=0}^{j-1}
    (\vec{q}_i^{\,\top} \vec{a}_j)\vec{q}_i \\
    \hat{q}^{\,,} &= \frac{\vec{q}_j^{\,\,,}}
    {||\vec{q}_j^{\,\,,}||}
\end{align*}

and also

\begin{align*}
    \mathsf{QR} &= \mathsf{A} \\
    \mathsf{R} &= \mathsf{Q^\top A}
\end{align*}

since $\mathsf{Q}$ is orthonomal, meaning $\mathsf{Q}^{-1} = \mathsf{Q}^\top$

In [303]:
# Taking the matrices from 5 to test with
A = [4 -1 -1  0;
    -1  4  0 -1;
    -1  0  4 -1;
     0 -1 -1  4]

b = [1; 2; 0; 1]
;

In [316]:
# Find orthonormal Q from columns of A
function gram_schmidt_QR(A)
    A = float.(A)
    n = length(diag(A))
    
    Q = zeros(n,n)

    for j ∈ 1:n
        other_vector_terms = zeros(n)
        for i ∈ 1:j-1
            q_i = Q[:, i]
            other_vector_terms += q_i' * A[:, j] * q_i
        end
        q_unnormal = A[:, j] - other_vector_terms
        Q[:, j] = q_unnormal / norm(q_unnormal) 
    end

    R = Q' * A

    return Q, R
end

gram_schmidt_QR (generic function with 1 method)

In [317]:
Q, R = gram_schmidt_QR(A)
;

In [ ]:
# check that QR is approximately A
Q*R ≈ A

true

In [320]:
x = back_sub(R, Q'b)

4-element Vector{Float64}:
 0.4999999999999999
 0.75
 0.24999999999999997
 0.49999999999999994

In [322]:
x ≈ A \ b

true

# Problem 9

In [ ]:
M_x = [0 1 0; 1 0 1; 0 1 0] / sqrt(2)
M_y = [0 -im 0; im 0 -im; 0 im 0] / sqrt(2)
M_z = [1 0 0; 0 0 0; 0 0 -1]
;

3×3 Matrix{Int64}:
 1  0   0
 0  0   0
 0  0  -1

### Test commutation relations

In [326]:
function commutator(A,B)
    return A*B - B*A
end

commutator (generic function with 1 method)

In [357]:
print("[M_x, M_y]:")
comm1 = commutator(M_x, M_y)

[M_x, M_y]:

3×3 Matrix{ComplexF64}:
 0.0+1.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0-1.0im

In [358]:
print("[M_y, M_z]:")
comm2 = commutator(M_y, M_z)

[M_y, M_z]:

3×3 Matrix{ComplexF64}:
 0.0+0.0im       0.0+0.707107im  0.0+0.0im
 0.0+0.707107im  0.0+0.0im       0.0+0.707107im
 0.0+0.0im       0.0+0.707107im  0.0+0.0im

In [359]:
print("[M_z, M_x]:")
comm3 = commutator(M_z, M_x)

[M_z, M_x]:

3×3 Matrix{Float64}:
  0.0        0.707107  0.0
 -0.707107   0.0       0.707107
  0.0       -0.707107  0.0

In [360]:
test = comm1 ≈ im*M_z
print("Does [M_x, M_y] = iM_z? $test")

test = comm2 ≈ im*M_x
print("\nDoes [M_y, M_z] = iM_x? $test")

test = comm3 ≈ im*M_y
print("\nDoes [M_z, M_x] = iM_y? $test")

Does [M_x, M_y] = iM_z? true
Does [M_y, M_z] = iM_x? true
Does [M_z, M_x] = iM_y? true

### $M^2 = M_x^2 + M_y^2 + M_z^2$

In [361]:
M_x * M_x + M_y * M_y + M_z * M_z

3×3 Matrix{ComplexF64}:
 2.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  2.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  2.0+0.0im

### The $L$ ones

In [362]:
L⁺ = M_x + im*M_y
L⁻ = M_x - im*M_y

comm4 = commutator(L⁺, L⁻)

3×3 Matrix{ComplexF64}:
 2.0+0.0im  0.0+0.0im   0.0+0.0im
 0.0+0.0im  0.0+0.0im   0.0+0.0im
 0.0+0.0im  0.0+0.0im  -2.0+0.0im

In [363]:
test = comm4 ≈ 2*M_z
print("\nDoes [L+, L-] = 2M_z? $test")


Does [L+, L-] = 2M_z? true

# Problem 10

In [367]:
L⁺ = [0 1 0; 0 0 1; 0 0 0]
L⁻ = [0 0 0; 1 0 0; 0 1 0]

ket_1 = [1;0;0]
ket_0 = [0;1;0]
ket_minus1 = [0;0;1]
;

In [368]:
L⁺ * ket_minus1

3-element Vector{Int64}:
 0
 1
 0

In [369]:
L⁻ * ket_minus1

3-element Vector{Int64}:
 0
 0
 0

In [370]:
L⁺ * ket_0

3-element Vector{Int64}:
 1
 0
 0

In [371]:
L⁻ * ket_0

3-element Vector{Int64}:
 0
 0
 1

In [372]:
L⁺ * ket_1

3-element Vector{Int64}:
 0
 0
 0

In [373]:
L⁻ * ket_1

3-element Vector{Int64}:
 0
 1
 0