# Lab 5  - Introduction to numpy.linalg


In this activity, we will learn how to do many common Linear Algebra tasks with `numpy.linalg` 

In [1]:
#import statement(s)
import numpy as np

Let's take a look at the methods (functions) inside of `numpy.linalg`. 
A handy way of doing this uses the 'dir' command. 

In [2]:
print(dir(np.linalg))

['LinAlgError', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_linalg', '_umath_linalg', 'cholesky', 'cond', 'cross', 'det', 'diagonal', 'eig', 'eigh', 'eigvals', 'eigvalsh', 'inv', 'linalg', 'lstsq', 'matmul', 'matrix_norm', 'matrix_power', 'matrix_rank', 'matrix_transpose', 'multi_dot', 'norm', 'outer', 'pinv', 'qr', 'slogdet', 'solve', 'svd', 'svdvals', 'tensordot', 'tensorinv', 'tensorsolve', 'test', 'trace', 'vecdot', 'vector_norm']


We can ignore the entries starting and ending with underscore. The remaining options are methods that we can use contained inside the class. We will look at a few examples below

## Example: Solving a system of coupled linear equations
Solve the coupled system of linear equations of the general form
$$
\mathsf{A} \mathbf{x} = \mathbf{b}.
$$

Our matrix A and vector b are defined below

In [3]:
A = np.array([
        [1, 5, 10],
        [2, 4, 8],
        [1, 0, 2]
    ])
b = np.array([9, 6, 3])

In [4]:
print("Matrix A:")
print(A)

print("Vector b:")
print(b)

Matrix A:
[[ 1  5 10]
 [ 2  4  8]
 [ 1  0  2]]
Vector b:
[9 6 3]


What does this look like as a system of equations?

In [5]:
for i in range(A.shape[0]):
    terms = []
    for j in range(A.shape[1]):
        terms.append("{1} x[{0}]".format(j, A[i, j]))
    print(" + ".join(terms), "=", b[i])

1 x[0] + 5 x[1] + 10 x[2] = 9
2 x[0] + 4 x[1] + 8 x[2] = 6
1 x[0] + 0 x[1] + 2 x[2] = 3


Now solve it with `numpy.linalg.solve`:

In [6]:
x = np.linalg.solve(A, b)
print(x)

[-1. -2.  2.]


Test that it satisfies the original equation:
$$
\mathsf{A} \mathbf{x} - \mathbf{b} = 0
$$

In [7]:
np.dot(A, x) - b

array([0., 0., 0.])

Note the difference in the quantities are zero (or at least consistent with zero at the level of machine precision), which verifies the solution.

## Activity 1: Solving matrix equations

Following the example above, solve the coupled system of linear equations of the form
$$
\mathsf{A} \mathbf{x} = \mathbf{b}.
$$

with
$$
\mathsf{A} = \left(\begin{array}{ccc}
   2 & 1 & 1\\
   1 & 1 & -2\\
   5 & 10 & 5
   \end{array}\right)
$$
and 

$$
\mathbf{b} = \left(\begin{array}{c}
   8 \\ -2 \\ +10
   \end{array}\right)  
$$


In [8]:
### Add Code to define A and b as shown in the cell above
A = np.array([[2,1,1],
              [1,1,-2],
              [5,10,5]])

b = np.array([8,-2,10])

Print and verify they are correct

In [9]:
print("Matrix A:")
print(A)

print("Vector b:")
print(b)

Matrix A:
[[ 2  1  1]
 [ 1  1 -2]
 [ 5 10  5]]
Vector b:
[ 8 -2 10]


Now use `np.linalg.solve()` to find $x$

In [10]:
x = np.linalg.solve(A, b)
print(x)

[ 4. -2.  2.]


Verify your solution

In [11]:
print(A.dot(x) - b)

[ 0.00000000e+00  4.44089210e-16 -1.77635684e-15]


## Activity 2: Finding the Matrix Inverse 

Let's find the inverse of $\mathsf{A}$. Recall that we have the relationship:
$$
\mathsf{A}\mathsf{A}^{-1} = \mathsf{A}^{-1}\mathsf{A} = \mathsf{1}
$$

First let's check that the inverse exists (remember singular matrcies don't have an inverse!)

In [12]:
det_A = np.linalg.det(A)

print(r"Determinate of A is: ", det_A)

if det_A != 0:
    print(r'The matrix A is not singular, the inverse can be found')
else:
    print(r'The matrix A is singular, the inverse cannot be found')

Determinate of A is:  40.0
The matrix A is not singular, the inverse can be found


The solution aove 'checks out', so we can use `numpy.linalg.inv()` can calculate the inverse:

In [13]:
Ainv = np.linalg.inv(A)
print("Matrix A^-1:")
print(Ainv)

Matrix A^-1:
[[ 0.625  0.125 -0.075]
 [-0.375  0.125  0.125]
 [ 0.125 -0.375  0.025]]


Check that our solution behaves like an inverse in that $\mathsf{A}\mathsf{A}^{-1} = \mathbf{I} $

In [14]:
### ADD YOUR CODE HERE
A @ Ainv

array([[ 1.00000000e+00,  5.55111512e-17, -2.08166817e-17],
       [ 5.55111512e-17,  1.00000000e+00, -1.38777878e-17],
       [-1.38777878e-16,  5.55111512e-17,  1.00000000e+00]])

Let's check our result from activity 1 using the matrix inverse:
$$
\mathbf{x} = \mathsf{A}^{-1} \mathbf{b}
$$

In [15]:
Ainv.dot(b)

array([ 4., -2.,  2.])

Verify the solution matches our earlier result. 